fleet:
  - robot_name: otto600
    robot_namespace: otto_1
    lane: npc1
    tasks_config_file: config/otto600_npc_stereo_task.yaml
    nav2_param_file: otto600Params.yaml
    position: 
      x: -26.0
      y: 27.0
      z: 0.1


