fleet:
  - robot_name: otto600
    robot_namespace: otto_1
    lane: Line1
    position: 
      x: -28.0
      y: 2.0
      z: 0.1


  - robot_name: otto600
    robot_namespace: otto_2
    lane: Line2
    position: 
      x: -26.0
      y: 2.0
      z: 0.2

  - robot_name: otto600
    robot_namespace: otto_3
    lane: Line1
    position: 
      x: -24.0
      y: 2.0
      z: 0.2

  - robot_name: otto600
    robot_namespace: otto_4
    lane: Line2
    position: 
      x: -22.0
      y: 2.0
      z: 0.2

arms:
  - namespace: ur1
    num_of_boxes: 18
    launch_rviz: false
  - namespace: ur2
    num_of_boxes: 18
    launch_rviz: false