/**:
  ros__parameters:
    loop: true
    tasks : ["Idle", "Loop1", "Loop2"]
    lifter_tasks : [""]
    pre_task_delays : [0.0, 0.0, 0.0]
    post_task_delays : [0.0, 0.0, 0.0]
    dummy_tasks: ["Idle"]
    blind_tasks: [""]
    blind_tasks_reverse: [""]
    cargo_load_tasks: [""]
    cargo_unload_tasks: [""]
    task_acquire_lock: [""]
    task_release_lock: [""]
