/otto_1/otto_deliberation_node:
    ros__parameters:
      tasks : ["idle", "Path1"]
      lifter_tasks : [""]
      pre_task_delays : [0.0, 0.0]
      post_task_delays : [0.0, 0.0]
      dummy_tasks: ["idle"]
      blind_tasks: ["Path1"]
      blind_tasks_reverse: [""]
      cargo_load_tasks: [""]
      cargo_unload_tasks: [""]
      tasks_with_lock: [""]