<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="OTTO1500">

  <xacro:property name="base_link_width" value="1.29" />
  <xacro:property name="base_link_length" value="1.83" />
  <xacro:property name="base_link_height" value="0.32" />
  <xacro:property name="base_link_box_height" value=".391179" />

  <xacro:property name="ground_clearence" value="0.1" />
  
  <xacro:property name="wheel_axis_front" value="0.601175" />
  <xacro:property name="wheel_axis_rear" value="-0.601175" />
  <xacro:property name="wheel_track" value="0.475812" />

  <xacro:property name="wheel_front_rear_radius" value="0.09" />
  <xacro:property name="wheel_front_rear_length" value="0.061434" />
  <xacro:property name="wheel_center_radius" value="0.147" />  
  <xacro:property name="wheel_center_length" value="0.1" />

  <xacro:property name="basic_platform_width" value="0.963" />
  <xacro:property name="basic_platform_length" value="1.53" />
  <xacro:property name="basic_platform_height" value="0.015" />
  <xacro:property name="basic_platform_offset" value="0.376" />
  <xacro:property name="basic_platform_collider_offset" value="0.005" />

  <xacro:property name="camera_height" value="0.22" />
  <xacro:property name="camera_center_offset" value="0.51" />

  <xacro:property name="lidar_height" value="0.1" />


  <link name="base_link">
    <inertial>
      <origin xyz="0. 0. 0." />
      <mass value="327" />
      <inertia ixx="49.84" ixy="0." ixz="0." iyy="136.60" iyz="0." izz="95.75"/>
    </inertial>
    <visual>
      <origin rpy="0. 0. ${pi/2}" xyz="0. 0. 0."/>
      <geometry>
        <mesh filename="../meshes/OTTO1500_bodylink.stl" scale="1.0 1.0 1.0" />
      </geometry>
    </visual>
    <collision>
      <origin rpy="0. 0. ${pi/2}" xyz="0. 0. ${base_link_height* (0.5 + ground_clearence/2)}"/>
      <geometry>
        <box size="${base_link_width} ${base_link_length} ${base_link_height}" />
      </geometry>
    </collision>
  </link>

  <!-- Wheel front left -->
  <link name="wheel_FL">
    <inertial>
      <origin xyz="0. 0. 0." />
      <mass value="5" />
      <inertia ixx="1." ixy="0." ixz="0." iyy="1." iyz="0." izz="1."/>
    </inertial>
    <visual>
      <origin rpy="0. 0. ${pi/2}" xyz="0. 0. ${-wheel_front_rear_radius}"/>
      <geometry>
        <mesh filename="../meshes/OTTO1500_wheel_front_rear.stl" scale="1.0 1.0 1.0" />
      </geometry>
    </visual>
    <collision>
      <origin rpy="${pi/2} ${pi/2} 0." xyz="0. 0. 0."/>
      <geometry>
        <cylinder radius="${wheel_front_rear_radius}" length="${wheel_front_rear_length}"/>
      </geometry>
    </collision>
  </link>
  <joint name="wheel_FL_joint" type="continuous">
    <parent link="base_link" />
    <child link="wheel_FL" />
    <axis xyz="0. 1. 0." />
    <origin rpy="0. 0. 0." xyz="${wheel_axis_front} ${wheel_track} ${wheel_front_rear_radius}" />
  </joint>

  <link name="wheel_FR">
    <inertial>
      <origin xyz="0. 0. 0." />
      <mass value="5" />
      <inertia ixx="1." ixy="0." ixz="0." iyy="1." iyz="0." izz="1."/>
    </inertial>
    <visual>
      <origin rpy="0. 0. ${pi/2}" xyz="0. 0. ${-wheel_front_rear_radius}"/>
      <geometry>
        <mesh filename="../meshes/OTTO1500_wheel_front_rear.stl" scale="1.0 1.0 1.0" />
      </geometry>
    </visual>
    <collision>
      <origin rpy="${pi/2} ${pi/2} 0." xyz="0. 0. 0."/>
      <geometry>
        <cylinder radius="${wheel_front_rear_radius}" length="${wheel_front_rear_length}"/>
      </geometry>
    </collision>
  </link>
  <joint name="wheel_FR_joint" type="continuous">
    <parent link="base_link" />
    <child link="wheel_FR" />
    <axis xyz="0. 1. 0." />
    <origin rpy="0. 0. 0." xyz="${wheel_axis_front} ${-wheel_track} ${wheel_front_rear_radius}" />
  </joint>

  <link name="wheel_CL">
    <inertial>
      <origin xyz="0. 0. 0." />
      <mass value="5" />
      <inertia ixx="1." ixy="0." ixz="0." iyy="1." iyz="0." izz="1."/>
    </inertial>
    <visual>
      <origin rpy="0. 0. ${pi/2}" xyz="0. 0. ${-wheel_center_radius}"/>
      <geometry>
        <mesh filename="../meshes/OTTO1500_wheel_center.stl" scale="1.0 1.0 1.0" />
      </geometry>
    </visual>
    <collision>
      <origin rpy="${pi/2} ${pi/2} 0." xyz="0. 0. 0."/>
      <geometry>
        <cylinder radius="${wheel_center_radius}" length="${wheel_center_length}"/>
      </geometry>
    </collision>
  </link>
  <joint name="wheel_CL_joint" type="continuous">
    <parent link="base_link" />
    <child link="wheel_CL" />
    <axis xyz="0. 1. 0." />
    <origin rpy="0. 0. 0." xyz="0. ${wheel_track} ${wheel_center_radius}" />
  </joint>

  <link name="wheel_CR">
    <inertial>
      <origin xyz="0. 0. 0." />
      <mass value="5" />
      <inertia ixx="1." ixy="0." ixz="0." iyy="1." iyz="0." izz="1."/>
    </inertial>
    <visual>
      <origin rpy="0. 0. ${pi/2}" xyz="0. 0. ${-wheel_center_radius}"/>
      <geometry>
        <mesh filename="../meshes/OTTO1500_wheel_center.stl" scale="1.0 1.0 1.0" />
      </geometry>
    </visual>
    <collision>
      <origin rpy="${pi/2} ${pi/2} 0." xyz="0. 0. 0."/>
      <geometry>
        <cylinder radius="${wheel_center_radius}" length="${wheel_center_length}"/>
      </geometry>
    </collision>
  </link>
  <joint name="wheel_CR_joint" type="continuous">
    <parent link="base_link" />
    <child link="wheel_CR" />
    <axis xyz="0. 1. 0." />
    <origin rpy="0. 0. 0." xyz="0. ${-wheel_track} ${wheel_center_radius}" />
  </joint>

  <link name="wheel_RL">
    <inertial>
      <origin xyz="0. 0. 0." />
      <mass value="5" />
      <inertia ixx="1." ixy="0." ixz="0." iyy="1." iyz="0." izz="1."/>
    </inertial>
    <visual>
      <origin rpy="0. 0. ${pi/2}" xyz="0. 0. ${-wheel_front_rear_radius}"/>
      <geometry>
        <mesh filename="../meshes/OTTO1500_wheel_front_rear.stl" scale="1.0 1.0 1.0" />
      </geometry>
    </visual>
    <collision>
      <origin rpy="${pi/2} ${pi/2} 0." xyz="0. 0. 0."/>
      <geometry>
        <cylinder radius="${wheel_front_rear_radius}" length="${wheel_front_rear_length}"/>
      </geometry>
    </collision>
  </link>
  <joint name="wheel_RL_joint" type="continuous">
    <parent link="base_link" />
    <child link="wheel_RL" />
    <axis xyz="0. 1. 0." />
    <origin rpy="0. 0. 0." xyz="${wheel_axis_rear} ${wheel_track} ${wheel_front_rear_radius}" />
  </joint>

  <link name="wheel_RR">
    <inertial>
      <origin xyz="0. 0. 0." />
      <mass value="5" />
      <inertia ixx="1." ixy="0." ixz="0." iyy="1." iyz="0." izz="1."/>
    </inertial>
    <visual>
      <origin rpy="0. 0. ${pi/2}" xyz="0. 0. ${-wheel_front_rear_radius}"/>
      <geometry>
        <mesh filename="../meshes/OTTO1500_wheel_front_rear.stl" scale="1.0 1.0 1.0" />
      </geometry>
    </visual>
    <collision>
      <origin rpy="${pi/2} ${pi/2} 0." xyz="0. 0. 0."/>
      <geometry>
        <cylinder radius="${wheel_front_rear_radius}" length="${wheel_front_rear_length}"/>
      </geometry>
    </collision>
  </link>
  <joint name="wheel_RR_joint" type="continuous">
    <parent link="base_link" />
    <child link="wheel_RR" />
    <axis xyz="0. 1. 0." />
    <origin rpy="0. 0. 0." xyz="${wheel_axis_rear} ${-wheel_track} ${wheel_front_rear_radius}" />
  </joint>

  <link name="basic_platform">
    <inertial>
      <origin xyz="0. 0. 0." />
      <mass value="15" />
      <inertia ixx="1." ixy="0." ixz="0." iyy="1." iyz="0." izz="1."/>
    </inertial>
    <visual>
      <origin rpy="0. 0. ${pi/2}" xyz="0. 0. ${basic_platform_offset}"/>
      <geometry>
        <mesh filename="../meshes/Platform_A.stl" scale="1.0 1.0 1.0" />
      </geometry>
    </visual>
    <collision>=
      <origin rpy="0. 0. ${pi/2}" xyz="0. 0. ${basic_platform_offset + basic_platform_collider_offset}"/>
      <geometry>
        <box size="${basic_platform_width} ${basic_platform_length} ${basic_platform_height}" />
      </geometry>
    </collision>
  </link>
  <joint name="platform_base_joint" type="fixed">
    <parent link="base_link" />
    <child link="basic_platform" />
    <origin rpy="0. 0. 0." xyz="0. 0. 0." />
  </joint>

  <link name="lidar_F" />
  <joint name="lidar_F_joint" type="fixed">
    <parent link="base_link" />
    <child link="lidar_F" />
    <origin rpy="0. 0. 0." xyz="${base_link_length * 0.47} ${base_link_width * 0.47} ${lidar_height}" />
  </joint>

  <link name="lidar_R" />
  <joint name="lidar_R_joint" type="fixed">
    <parent link="base_link" />
    <child link="lidar_R" />
    <origin rpy="0. 0. 0." xyz="${-base_link_length * 0.47} ${-base_link_width * 0.47} ${lidar_height}" />
  </joint>

  <link name="camera_FL" />
  <joint name="camera_FL_joint" type="fixed">
    <parent link="base_link" />
    <child link="camera_FL" />
    <origin rpy="0. 0. 0." xyz="${base_link_length / 2} ${camera_center_offset} ${camera_height}" />
  </joint>

  <link name="camera_FR" />
  <joint name="camera_FR_joint" type="fixed">
    <parent link="base_link" />
    <child link="camera_FR" />
    <origin rpy="0. 0. 0." xyz="${base_link_length / 2} ${-camera_center_offset} ${camera_height}" />
  </joint>

  <link name="camera_RL" />
  <joint name="camera_RL_joint" type="fixed">
    <parent link="base_link" />
    <child link="camera_RL" />
    <origin rpy="0. 0. 0." xyz="${-base_link_length / 2} ${camera_center_offset} ${camera_height}" />
  </joint>

  <link name="camera_RR" />
  <joint name="camera_RR_joint" type="fixed">
    <parent link="base_link" />
    <child link="camera_RR" />
    <origin rpy="0. 0. 0." xyz="${-base_link_length / 2} ${-camera_center_offset} ${camera_height}" />
  </joint>

</robot>
